# Generated a main.py file that sets up a sample owner, pets, and tasks, then prints today's schedule in a nice format. 
# This serves as a demonstration of how the PawPal+ system works and can be used as a starting point for further development or testing.
# Generated by ClaudeCode 

from datetime import datetime
from pawpal_system import Task, Pet, Owner, Scheduler

# --- Setup Owner ---
owner = Owner("Alex Rivera", "alex@pawpal.com")
scheduler = Scheduler(owner)

# --- Create Pets ---
rex = Pet("Rex", "Dog", 4)
luna = Pet("Luna", "Cat", 2)
owner.add_pet(rex)
owner.add_pet(luna)

# --- Add Tasks to Rex ---
today = datetime.now().replace(second=0, microsecond=0)

rex.add_task(Task(
    title="Morning Walk",
    description="30 min walk around the neighborhood",
    due_time=today.replace(hour=7, minute=30),
    frequency="daily",
    category="walk"
))
rex.add_task(Task(
    title="Breakfast",
    description="2 cups dry kibble",
    due_time=today.replace(hour=8, minute=0),
    frequency="daily",
    category="feeding"
))
rex.add_task(Task(
    title="Flea Medication",
    description="Apply topical flea treatment between shoulder blades",
    due_time=today.replace(hour=9, minute=0),
    frequency="weekly",
    category="medication"
))

# --- Add Tasks to Luna ---
luna.add_task(Task(
    title="Vet Checkup",
    description="Annual wellness exam — bring vaccination records",
    due_time=today.replace(hour=11, minute=0),
    frequency="once",
    category="appointment"
))
luna.add_task(Task(
    title="Lunch",
    description="Half can of wet food",
    due_time=today.replace(hour=13, minute=0),
    frequency="daily",
    category="feeding"
))
luna.add_task(Task(
    title="Evening Playtime",
    description="15 min with feather wand",
    due_time=today.replace(hour=18, minute=30),
    frequency="daily",
    category="walk"
))

# --- Print Today's Schedule ---
print("=" * 50)
print("       🐾  PawPal+ — Today's Schedule")
print("=" * 50)
print(f"  Owner : {owner.name}")
print(f"  Pets  : {', '.join(p.name for p in owner.get_pets())}")
print("=" * 50)

todays_tasks = scheduler.sort_by_time()  # chronological order

if not todays_tasks:
    print("  No tasks scheduled for today.")
else:
    current_pet = None
    for task in todays_tasks:
        # Find which pet owns this task
        pet_name = next(
            (p.name for p in owner.get_pets() if task in p.tasks), "Unknown"
        )
        if pet_name != current_pet:
            current_pet = pet_name
            print(f"\n  [{pet_name}]")

        status = "✓" if task.is_completed else " "
        priority_tag = f"[{task.priority.upper()}]".ljust(8)
        time_str = task.due_time.strftime("%I:%M %p")
        print(f"  [{status}] {time_str}  {priority_tag}  {task.title}")
        print(f"            {task.description}")

print("\n" + "=" * 50)
print(f"  Total tasks today : {len(todays_tasks)}")
print(f"  High priority     : {sum(1 for t in todays_tasks if t.priority == 'high')}")
print(f"  Pending           : {sum(1 for t in todays_tasks if not t.is_completed)}")
print("=" * 50)
